### PR TITLE
Update svg

### PR DESCRIPTION
**Pull request by ghost**
@reviewmerge @jeremyfelt @philcable 

* Updates the SVG chart per Allen's request to be larger and add back the number of startups

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@charlesjdillon it looks like this includes @philcable's changes from #21. Is that intentional?

**Comment by ghost** [comment]
@jeremyfelt https://github.com/washingtonstateuniversity/research.wsu.edu/pull/24/commits/58700982869194180801fba11e8a9dbe89dbc225 This should show that it was removed. Am I missing something?

**Comment by jeremyfelt** [comment]
@charlesjdillon That commit changes the SVG in `functions.php`, but the commits in db7878b, e57c89c, fddb4ac, 92886ae, and bc04791 are still part of this branch.

It may be worth creating a new branch off of master and committing your changes fresh on that.

**Comment by ghost** [comment]
@jeremyfelt The goal was trying to get the new SVG graph up without the animation. The new branch should of been update-svg and the animation branch is the svg-animation.

**Comment by jeremyfelt** [comment]
It looks like the `update-svg` branch (this one), was accidentally branched off of `svg-animation` rather than `master`.

See the list of changes - https://github.com/washingtonstateuniversity/research.wsu.edu/pull/24/files - and commits - https://github.com/washingtonstateuniversity/research.wsu.edu/pull/24/commits - on this PR.

If we merge this PR, all of those changes will be committed.

**Pull request closed without merging**
